### PR TITLE
skip symlinks pointing to a directory, and degenerate symlinks

### PR DESCRIPTION
**Pull request by mhaberler**
here's a draft PR - let me know what you think

### CODE REVIEW

**Comment by mhaberler** [comment]
hm, this seems to work for '-c .', but not for '-c <somedir>'

**Comment by mhaberler** [comment]
that's more like it

@earlephilhower would you test-drive this and check for obvious blunders?

**Comment by mhaberler** [comment]
this still fails at symlinks pointing to an absolute pathname, but getting there

**Comment by mhaberler** [comment]
I'm out of my depth adapting this to Windows and other platforms, and I can only guess how proper indentation in this code works

other than that, works for me now

**Comment by earlephilhower** [comment]
Wow, very comprehensive checks!  Let me pull this on a WIN32 box this week and try the build there.  I'm not worried about NTFS junctions, nobody uses them, so if the `lstat` turns into no-ops all should be well.  But I'm not 100% sure how mingw32 works w/the lstat and associated macros

**Comment by mhaberler** [comment]
very kind of you, thanks!

**Review by earlephilhower — CHANGES_REQUESTED** [review]
I like the changes, but can you please bracket them with a `#if !defined(_WIN32)` because the mingw subsystem does not have the lstat or the S_ISLNK macros.


````
x86_64-w64-mingw32-g++ -std=gnu++11 -Os -Wall   -Itclap -Iinclude -Ilittlefs -I. -D VERSION=\"0.2.3-34-ge465999\" -D LITTLEFS_VERSION=\"v2.0.5\" -D BUILD_CONFIG=\"-DSPIFFS_USE_MAGIC_LENGTH=0\\x20-DSPIFFS_ALIGNED_OBJECT_INDEX_TABLES=1\" -D BUILD_CONFIG_NAME=\"-arduino-esp8266\" -D __NO_INLINE__ -D LFS_NAME_MAX=32 -DSPIFFS_USE_MAGIC_LENGTH=0 -DSPIFFS_ALIGNED_OBJECT_INDEX_TABLES=1  -c -o main.o main.cpp
main.cpp: In function 'int addFiles(const char*, const char*)':
main.cpp:257:17: error: 'lstat' was not declared in this scope
                 lstat(name.c_str(), &path_stat);
                 ^~~~~
main.cpp:257:17: note: suggested alternative: 'wstat'
                 lstat(name.c_str(), &path_stat);
                 ^~~~~
                 wstat
main.cpp:258:24: error: 'S_ISLNK' was not declared in this scope
                 while (S_ISLNK(path_stat.st_mode) && loopcount > 0) {
                        ^~~~~~~
main.cpp:258:24: note: suggested alternative: 'S_ISBLK'
                 while (S_ISLNK(path_stat.st_mode) && loopcount > 0) {
                        ^~~~~~~
                        S_ISBLK
main.cpp:260:36: error: 'readlink' was not declared in this scope
                     ssize_t size = readlink(target.c_str(), buf, sizeof buf);
                                    ^~~~~~~~
main.cpp:260:36: note: suggested alternative: 'readdir'
                     ssize_t size = readlink(target.c_str(), buf, sizeof buf);
                                    ^~~~~~~~
                                    readdir
main.cpp:273:39: error: 'realpath' was not declared in this scope
                     const char *ptr = realpath(target.c_str(), rpath);
                                       ^~~~~~~~
main.cpp:273:39: note: suggested alternative: 'rpath'
                     const char *ptr = realpath(target.c_str(), rpath);
                                       ^~~~~~~~
                                       rpath
main.cpp:288:21: error: 'S_ISLNK' was not declared in this scope
                 if (S_ISLNK(path_stat.st_mode) && name.compare(target) == 0) {
                     ^~~~~~~
main.cpp:288:21: note: suggested alternative: 'S_ISBLK'
                 if (S_ISLNK(path_stat.st_mode) && name.compare(target) == 0) {
                     ^~~~~~~
                     S_ISBLK
<builtin>: recipe for target 'main.o' failed
````

**Review by earlephilhower — APPROVED** [review]
I've added the ifdefs in your branch so it can be merged.  Thx!

**Pull request merged**
